spring:
  application:
    name: corpodash

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret

  sql:
    init:
      mode: always
      data-locations: classpath:db/seed/dev-data.sql

  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true


security:
  jwt:
    issuer: corpodash
    secret-key: mysecret
    expiry-time-in-seconds: 86400
